In [ ]:
# 1-1
import numpy as np

A = np.array([[1, 3], [2, 3], [-1, 0]])
B = np.array([[0, 0, 2], [1, 4, -2], [3, 1, -1], [2, 0, 2]])

In [ ]:
# 1-2

result = []

num1 = 0
num2 = 0
num3 = 0

for i in range(len(B)):
  for j in range(len(A[0])):
    num1 = B[i][0] * A[0][j]
    num2 = B[i][1] * A[1][j]
    num3 = B[i][2] * A[2][j]

    print(np.array([num1, num2, num3]))           # 각 배열의 요소를 곱한 결과
    result.append(np.array([num1, num2, num3]))

print(np.sum(result))

[ 0  0 -2]
[0 0 0]
[1 8 2]
[ 3 12  0]
[3 2 1]
[9 3 0]
[ 2  0 -2]
[6 0 0]
48
